#!/bin/sh

if [ "x$1" = "x" ]; then
         cd /home/seo/iptv/epg2xml-master
         /usr/bin/python epg2xml.py
    exit 0
fi

case "$1" in
    --description)
    echo "My custom grabber"
    ;;
    --version)
    echo "1.0"
    ;;
    --capabilities)
    echo "baseline"
    ;;
esac

